version: '3.8'

services:
  spring-backend:
    build:
      context: ./Spring-Backend
      dockerfile: Dockerfile
    image: bank-system-backend:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bank_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Asdzxc123!
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    networks:
      - network1

  spring-frontend:
      build:
        context: ./Spring-Frontend
        dockerfile: Dockerfile
      image: bank-system-frontend:latest
      container_name: spring-frontend
      ports:
        - "8081:8081"
      networks:
        - network1
      depends_on:
        - spring-backend

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Asdzxc123!
      MYSQL_DATABASE: bank_system
      MYSQL_USER: user
      MYSQL_PASSWORD: Asdzxc123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network1


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "3307:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Asdzxc123!
    depends_on:
      - db
    networks:
      - network1

networks:
  network1:

volumes:
  mysql_data: